### ISSUE TITLE
Add intersperse

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/purescript-foldable-traversable#114]
Every once in a while, I find myself needing this. 
Then I find [this](https://github.com/purescript/purescript-lists/issues/132) again. And then I go look it up [here](https://hackage.haskell.org/package/base-4.14.0.0/docs/src/Data.OldList.html#intersperse).

I don't know about the performance characteristics but I could translate the Haskell version into PS.

**Comment by i-am-the-slime** [comment]
Maybe it doesn't belong here, but to Array and friends?

**Comment by hdgarrood** [comment]
I agree, I’ve wanted this too, and using `intercalate` is less than ideal, not only because it’s slower, but also because I find it’s surprisingly hard to work out how to get the types to line up to get it to do what I want. I think adding monomorphic `forall a. a -> T a -> T a` functions for T = Array, List, etc would be the way to go. Foldable doesn’t quite seem appropriate because it doesn’t really give you a good way of preserving structure; I think an implementation in terms of Foldable would have to rely on a Semigroup instance which does concatenation.

**Comment by hdgarrood** [comment]
I'll close this as I think it's covered by https://github.com/purescript/purescript-arrays/issues/15 and https://github.com/purescript/purescript-lists/issues/132, and we wouldn't put these functions in this library.
