### ISSUE TITLE
Why is the argument order of foldr and foldl switched up?

### ISSUE THREAD

**Issue by f6ADt** [purescript/purescript-foldable-traversable#126]
Has there been a reason to switch up the argument order of `a` and `b` inside the accumulator function [for `foldl` and `foldr`](https://github.com/purescript/purescript-foldable-traversable/blob/ea905c3/src/Data/Foldable.purs#L65-L66)?
I find this super confusing and have to look it up every time, I do something with `Foldable`s.

If there isn't a reason: I would be in favor of a breaking change coming with a *major* version unifying these function signatures - less mental overhead. `forall a b. (b -> a -> b) -> b -> f a -> b` would be the more suitable one IMO, as JavaScript developers are used to [ `Array.prototype.reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) and [`Array.prototype.reduceRight`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/ReduceRight).

**Comment by hdgarrood** [comment]
Yes, the reason is that writing out what these functions actually do becomes _much_ simpler this way:
```
foldr f z (a:b:c:Nil) = a `f` (b `f` (c `f` z))
foldl f z (a:b:c:Nil) = (((z `f` a) `f` b) `f` c)
```

**Comment by garyb** [comment]
The arguments are switched to echo the direction of the fold. I get tripped up by JavaScript _not_ reversing the arguments :smile:.

Consider these functions:

- `List.Cons :: x -> List x -> List x`
- `List.snoc :: List x -> x -> List x`

The arguments are flipped here because it aligns with how the item is joined to the list. `Cons` adds an element to the start of the list, `snoc` to the end.

If you look at folds as a structural transformation, the `f` in `foldr` is like the purpose of `Cons`, and the `f` in `foldl` is `snoc`. The same reason we flip the arguments of the list operations is the reason it makes sense to do so when they're used in a fold also.

**Comment by f6ADt** [comment]
@hdgarrood @garyb thanks for the quick answer, at least good to know that this is a conscious decision.

I must admit, I am not 100% convinced, but that probably is more due to my limited experience with PureScript - you may have read through the lines, that I am coming from JS background, not Haskell.

@garyb in a way, we are in the same boat then 😂.
