### ISSUE TITLE
scanl misses the intial value

### ISSUE THREAD

**Issue by csabahruska** [purescript/purescript-foldable-traversable#23]
haskell: scanl (+) 0 [1,1] == [0,1,2]
purescript: scanl (+) 0 [1,1] == [1,2]

**Comment by hdgarrood** [comment]
Given that the PureScript version is more general - it works with any `Traversable`, rather than Haskell's, which only works with `[]` - I am fairly sure it is not possible to preserve the Haskell behaviour with the current type.

However, it would be a shame to lose the generality, and I think the current behaviour is ok, as long as it's clearly documented.

**Comment by sharkdp** [comment]
I think @hdgarrood is correct: the Haskell behavior cannot be preserved with the general type signature. We have
```purescript
scanl (flip const) :: forall a t. (Traversable t) => a -> t a -> t a
```
In Haskell, `scanl (flip const)` is identical to `(:)`. So this would be a prepend (`cons`) operation on the Traversable, which is not supported.

**Comment by sharkdp** [comment]
I think @hdgarrood is correct: the Haskell behavior cannot be preserved with the general type signature. We have
```purescript
scanl (flip const) :: forall a t. (Traversable t) => a -> t a -> t a
```
In Haskell, `scanl (flip const)` is identical to `(:)`. So this would be a prepend (`cons`) operation on the Traversable, which is not supported.

**Comment by Fresheyeball** [comment]
:+1:  for general, also `Data.List.scanl` could exist.
