### ISSUE TITLE
Generic filter/etc

### ISSUE THREAD

**Issue by AppShipIt** [purescript/purescript-foldable-traversable#44]
## Problem

The collection packages are monomorphic for functions like (but not limited to) `filter` with a couple pain points:

1. They're inconvenient to use in conjunction without aliasing (e.g. `List` vs `Array`) also noted by @aspidites in tfausak/purescript-batteries#1.
2. They're inconvenient to switch out collection types to compare relative performance (thus encouraging `Array` use). The primary reason is type signatures must include the specialized type instead of class.

## Defense

@paf31 postulated with @garyb about the [potential issues][critique] of a type class solution:

1. Lack of mathematical precedence for laws.
2. Degraded performance because type class instances are currently never inlined (even when safe to do so).
3. More complex type signatures because of type class constraints. I'll add to that occasionally ambiguous inference and less friendly type errors but those are also true of this package.

## Options

- Naive `Cons`
  - @michaelficarra implemented a [naive approach][Consable] for `filter`.
  - @AppShipIt took the [same tack][naive Cons] for `partition` except with `singleton` instead of `empty` to support [`NonEmpty`][NonEmpty] types.
- Optical `Cons`
  - @joneshf predictably [implemented][optical Cons] `Cons` using `Prism` with examples in purescript/purescript#607.
- `MonadPlus`
  - @antti [demoed][MonadPlus] `partition`, et.al. using `MonadPlus`.
- `(Foldable f, Unfoldable f) <=` “Refoldable”
  - @jdegoes suggested [`Unfoldable`][Unfoldable] along with @joneshf in purescript/purescript-monoid#6 but I [encountered issues][refoldable issues] attempting it.
- `Witherable`
  - @joneshf alternatively recommended [`Witherable`][Witherable] in Haskell.
- Transducers
  - @tfausak noted (or I incorrectly inferred) `Cons` strikingly resembles [Clojure's `seq`][Clojure seq].
  - @manzyuk wrote about lawful [`MonoidalTransducer`][MonoidalTransducer].
  - @Gabriel439 pointed to his [`Foldl.Handler`][Foldl] in Haskell for inspiration.

## Conclusion

`Witherable` is motivated similarly in design to `Unfoldable` and looks like the right fit for standard Prelude. `Foldl` adds the benefit of laziness and working with optics. `Cons` and likewise `MonadPlus` _feel_ like their requirements are too specific for generic `filter`ing but I haven't tried to think of counterexamples yet.

## CC

- purescript/purescript#1075
- @bodil
- @drboolean
- @matthieubulte

[Clojure seq]: http://clojure.org/reference/sequences
[Consable]: https://github.com/michaelficarra/purescript-filterable/blob/master/src/Data/Filterable.purs
[critique]: http://chrisdone.com:10001/browse/purescript?id=92973&timestamp=1430514034
[Foldl]: https://hackage.haskell.org/package/foldl-1.1.5/docs/Control-Foldl.html#t:Handler
[Lens]: https://pursuit.purescript.org/packages/purescript-profunctor-lenses/0.4.0
[MonadPlus]: https://github.com/anttih/purescript-monadplus-partial/blob/master/src/Control/MonadPlus/Partial.purs
[MonoidalTransducer]: https://oleksandrmanzyuk.wordpress.com/2014/08/09/transducers-are-monoid-homomorphisms/
[naive Cons]: http://try.purescript.org/?gist=d94ccab2e99d4d052897
[NonEmpty]: https://pursuit.purescript.org/packages/purescript-nonempty/0.1.3/docs/Data.NonEmpty
[optical Cons]: https://github.com/joneshf/purescript-cons/blob/master/src/Optic/Cons.purs
[refoldable issues]: https://twitter.com/AppShipIt/status/694717112204525568
[Unfoldable]: https://pursuit.purescript.org/packages/purescript-unfoldable/0.4.1
[Witherable]: https://hackage.haskell.org/package/witherable-0.1.3.2/docs/Data-Witherable.html

**Comment by michaelficarra** [comment]
@AppShipIt Filter cannot be implemented on non-empty types, as `filter (const false)` must always produce the empty instance.

**Comment by AppShipIt** [comment]
My gist returned `Maybe` although not necessarily as friendly.

**Comment by Gabriel439** [comment]
You don't need `Consable` if you already have `Alternative`:

```haskell
cons :: Alternative f => a -> f a -> f a
cons x xs = pure x <|> xs
```

`filter` can be implemented in terms of `MonadPlus` (see Haskell's `Control.Monad.mfilter`) or the `Witherable` class (which has nice laws)

The main issue with `Consable` is that it lacks an elegant mathematical basis

**Comment by AppShipIt** [comment]
@Gabriel439 I started out implementing `partition` with `Alternative` but @paf31 pointed out it's unperformant because `cons` is potentially quadratic (e.g. `List`). I did leave an instance for `Plus` however ([gist](http://try.purescript.org/?gist=097d0b97a6318ac928d4)):
```purs
instance consPlusApplicative :: (Plus a, Applicative a) => Cons a where
  cons = alt <<< singleton
  singleton = pure
```
Lawlessness is Phil's concern too and thinks optics are the answer (e.g. @joneshf's `Cons`). I'm keen on reading into `Withering` and your `Foldl` too. Just looking for the best solution to my two pain points.

**Comment by Gabriel439** [comment]
The nice thing about `Witherable` is that there are two very obvious laws for `filter`, which are functor laws:

```haskell
filter (pure True) = id
filter (liftA2 (&&) f g) = filter f . filter g
```

... and if Purescript had `Semiring` instances for `Boolean`s and functions, then this would just be:

```haskell
filter one = id
filter (f * g) = filter f . filter g
```

**Comment by AppShipIt** [comment]
Thanks so much for your input! It looks like a strong contender. Regarding laws I also read about their [pertinence to transducers](https://oleksandrmanzyuk.wordpress.com).

**Comment by jdegoes** [comment]
My suggestion for `Unfoldable` / `Foldable` was more pedagogical (it can be done but it is not performant).

My real 2 cents: if you want performant, generic collection methods, you need to take a type class based approach. Because no matter what abstraction you choose to build methods like `partition`, `nub`, etc., you can't achieve good performance across the different base collection types (`Array`, `List`).

```purescript
class (Monad f) <= Collection f where
  partition :: forall a. (a -> Boolean) -> f a -> Tuple (f a) (f a)
  ...
```

You may cry, "Duplication!" Indeed, every different type of data structure will need its own definition of these functions. But that's sort of the point: every different data structure is optimized for certain use cases, so if you want a bunch of the *same* functions to work across them, they're going to have to be specialized (look at optimized definitions of `partition` for `List` and `Array`; they're totally different).

Even this approach will not achieve optimal performance when chaining collection methods, because it's too eager: you'd like to be able to fuse various operations together. For that case, you could require the user convert from a base data structure into a lazy, fuseable representation, and then from there into a polymorphic target representation via a builder class that allows efficient `ST`-based collection building.

It will be more verbose for the user (e.g. `[1, 2, 3] # stage >>> filter (_ > 2) >>> map (_ % 2) >>> build`), but you will have more predictable performance and less duplication.

For the case where we only care about reuse and not performance, I think PureScript needs a good recursion schemes library based on fixed point data, which could be used to build a lot of very generic and reusable collection-style methods (generalized to more types of data structures).

That's 3 totally different approaches that I think could all exist and find use in different scenarios. :smile:

**Comment by AppShipIt** [comment]
@jdegoes My main goal is too be able to switch out implementations at mid-development without rewriting type signatures (e.g. trying `Array`, `List`, `Seq`, and considering `Set`). Duplication isn't a concern but default implementations would be nice (e.g. `Folable`'s or my `Alternative` instance). There remains a potential issue passing an extra dictionary around but I suspect that'll lessen in the future with safe inlining. Regarding lazy chaining I recently read about [lawful transducers](https://oleksandrmanzyuk.wordpress.com/2014/08/09/transducers-are-monoid-homomorphisms/).

**Comment by Gabriel439** [comment]
Yep!  The `foldl` library has almost the exact same type, but it's called `Handler`:

http://hackage.haskell.org/package/foldl-1.1.5/docs/Control-Foldl.html#t:Handler

```haskell
type Handler a b = forall x. (b -> Constant (Endo x) b) -> a -> Constant (Endo x) a
```

The nice thing about this type is that any lens or traversal will type-check as the above type, so you can reuse all existing lenses or transversals as transducers, too.

**Comment by jdegoes** [comment]
Gabriel has a nice implementation of lawful transducers: <https://hackage.haskell.org/package/foldl-1.1.2/docs/Control-Foldl.html>

There's another package that adds some more goodies on top of that one: <https://hackage.haskell.org/package/foldl-transduce-0.4.7.0>

**Comment by Gabriel439** [comment]
Carefully note that the `Handler` type is the real analog to Clojure's transducers (not the `Foldl` type)

**Comment by paf31** [comment]
I was wrong about the quadratic performance of using `<|>`, or thinking of something else. My main problem with using `Alt` to build `cons` is that it doesn't allow for things like streams. This makes me wonder if `<|>` is the wrong sort of higher-order monoidal structure we want, although I'm really not sure. I think of `Alt` as modeling non-determinism, and how the semantics of how that interacts with the `Monoid` structure on things like `List` is unclear to me.

If lawfulness is the main concern, then we can always add more operations and laws, so I'm not sure how much faith to put in a type class just because it has some laws. I think it is better to judge a type class based on how time-tested its mathematical basis is, so something like a group or lattice or functor etc. makes a good type class, but `Consable` is a bit more shaky.

Although, if we extend `Consable` to assert that a container `c` is isomorphic to a coproduct of something with the product of itself with the identity functor, then that certainly has a solid mathematical basis, and extends nicely to streams. This is a lot like @joneshf 's `Cons` class approach based on `Prism`.

I'm also interested in `Witherable`.

**Comment by Gabriel439** [comment]
Actually, using `(<|>)` for cons does work with streams, or at least it does in Haskell.

Thinking of `Alt` as non-determinism is just as misleading as thinking of `Monoid` as multiplication.  The only property that matters for the `Alt` class is that `(<|>)` is associative and `empty` is its identity.  The fact that it's named `Alternative` doesn't really mean anything and is just an artifact of its history.  I just think of it as a higher-kinded `Monoid` class.

**Comment by paf31** [comment]
I'm thinking of infinite streams so that you can't define any `pure` such that `cons a` is `pure a <|>`.

**Comment by paf31** [comment]
Yes, but it interacts with `Applicative` too.

**Comment by Gabriel439** [comment]
Yeah, I think the `Applicative` super-class of `Alternative` is a mistake.  A super-class should always be implementable from the methods of the sub-class.

Here's a possible suggestion for a `Cons`-like class:

```haskell
{-| Laws:

> prepend [] = id
> prepend (xs ++ ys) = prepend xs . prepend ys
-}
class Prepend f where
    prepend :: [a] -> f a -> f a

cons :: Prepend f => a -> f a -> f a
cons x = prepend [x]

**Comment by AppShipIt** [comment]
> I was wrong about the quadratic performance of using <|>

@paf31 My original implementation without `Cons` did suffer from it.

@ALL I rewrote my description to capture the various approaches to make more collection functions polymorphic. I plan to delve into optical `Cons`, `Witherable`, and `Foldl`. Can anyone articulate pros/cons between those three (perhaps naive `Cons` too)? I think “refoldable” incurs a performance penalty and `MonadPlus` an unacceptable constraint. I do view laziness as highly desirable to reduce iteration.

**Comment by paf31** [comment]
> Yeah, I think the Applicative super-class of Alternative is a mistake.

I don't know, `Applicative` says "I want both" where `Alt` says "I want one", and I think that interaction is useful, compared to just a `Monoid` at kind `* -> *`. 

So perhaps the better instance context for the `Alt` approach is something like `(Applicative f, Semigroup1 f) => ...`, since we don't require the interaction with `Applicative`.

Thinking about laws, some things we might want to prove which could act as benchmarks:

- `filter (pure true) = id`
- `filter (lift2 (&&) f g) = filter f <<< filter g`

**Comment by AppShipIt** [comment]
> My main problem with using Alt to build cons is that it doesn't allow for things like streams.

@paf31 This just clicked for me this morning. A requirement in my opinion should be `filter` and `scan` for `Signal` and `Rx.Observable` too. `Cons` (optical or otherwise) is out but I want to compare `MonadPlus`.

**Comment by AppShipIt** [comment]
> Yes, but it interacts with `Applicative` too.

@paf31 `Alt` interacts with `Applicative`? That went over my head.

**Comment by Gabriel439** [comment]
There's one other thing I wanted to mention: you should be very careful about making type classes for every operation.  If you do this users will begin to get ambiguous type errors everywhere.  You have the most risk of this happening when you have functions with a return type that is polymorphic over one class that are fed into a function that is polymorphic over another class like the classic `show . read` example.

For example, any `Cons`-like class is at a high risk of clashing with the `Foldable` class and leading to ambiguous type errors.  In fact, the `Foldable` class in general tends to cause lots of issues with type inference.

**Comment by AppShipIt** [comment]
I considered that. I'd rather tackle explaining errors better (an area I'd like to contribute) than make it hard to switch out data structures (updating signatures everywhere). Haskell disambiguates by prefix (e.g. `fmap` vs `map`) which I found confusing starting out (“Why two? Fwhat does ‘f’ mean?”). I wonder if there's a clever compromise hiding.

**Comment by Gabriel439** [comment]
So in the case of Haskell we have a workaround in `ghc-8.0` that will greatly alleviate the solution, which is type application.  So, for example, if you want a `length` function specialized to lists you would just write `length @[]` and now it's monomorphic instead of polymorphic over `Foldable`.

If Purescript had something similar then I would have much fewer reservations about type-classing everything.

**Comment by AppShipIt** [comment]
PS has [asTypeOf](https://pursuit.purescript.org/packages/purescript-prelude/0.1.4/docs/Prelude#v:asTypeOf) but that sounds much nicer. CC @paf31?

**Comment by AppShipIt** [comment]
> `Witherable` is motivated similarly in design to Unfoldable and looks like the right fit for standard Prelude. `Foldl` adds the benefit of laziness and working with optics.

I added my personal conclusion in the issue description. @paf31 May I move `Witherable`/`Foldl` to the roadmap and close this one?

**Comment by paf31** [comment]
`Witherable` should be implemented in a `contrib` project, and then we can decide if it's a good fit for core.

**Comment by AppShipIt** [comment]
That makes sense. Is `contrib` in `roadmap` too? Closing regardless since it's beyond the scope of FTP.

**Comment by michaelficarra** [comment]
@AppShipIt Please post a link to the repo here once you create it so we can follow the progress of this issue.

**Comment by AppShipIt** [comment]
I will thanks @michaelficarra! It won't be until after LambdaConf because I'm working on 3 tools until then but making more list-like combinators polymorphic is on my personal todo.
