### ISSUE TITLE
FFI?

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript-foldable-traversable#49]
There are two ffi files here, both for array. Does it still make sense to keep them here? Or does it make more sense to move them to `purescript-arrays`? Near as I can tell, there's no direct dependency on arrays here, and arrays actually depends on this package instead of the other way around.

**Comment by paf31** [comment]
I can't remember the exact reason, but there was a subtle reason for the current dependency order and having the instance here. Maybe @garyb can recall?

**Comment by joneshf** [comment]
I feel like this is something I ask every so often and forget. Assuming it's decided to keep the instances here, how would you feel about a PR to add the information to the readme?

**Comment by paf31** [comment]
Sounds great!

**Comment by hdgarrood** [comment]
The reason they're here is that these instances can't go into `purescript-arrays`, because then they'd be orphans. The `Array` type is defined in `Prim`, so any Array instances must go either in `Prim` or in the module that defines the class, and we want to keep the amount of code bundled with the compiler as small as we possibly can (which rules out putting them in `Prim`).

**Comment by hdgarrood** [comment]
I can't remember why we have organised the core libraries with the current dependency order though. If we were to rearrange it so that `foldable-traversable` depended on `arrays`, it might well make sense to move the monomorphic `foldlArray` etc into `arrays`. If we did that, the `Foldable Array` instance would still have to stay in `foldable-traversable` though.

**Comment by garyb** [comment]
> I can't remember why we have organised the core libraries with the current dependency order though.

It evolved out of the requirements of the relationships between types and classes, especially since orphans were disallowed. It might not be the only valid order there is though, so if you can figure out if the dependencies all work out then doing that seems reasonable to me... although a little odd also if you're looking at the order "semantically".

The fact that array is magic is the problem really. If it wasn't in `Prim` we could do it properly, but without overloaded literals we can't do anything about it I guess.

**Comment by hdgarrood** [comment]
I'm closing as this appears to have been resolved.
